version: "3"
services:
  app:
    restart: "always"
    build: .
    ports:
      - "5001:5000"
    container_name: app
    command: uwsgi --ini uwsgi.ini
    links:
      - postgresql
    volumes:
      - weko3_data:/var/tmp
      - static_data:/home/invenio/.virtualenvs/invenio/var/instance/static
      - data_data:/home/invenio/.virtualenvs/invenio/var/instance/data
      - conf_data:/home/invenio/.virtualenvs/invenio/var/instance/conf
      - socket:/tmp
      - type: bind
        source: ./app
        target: /usr/src/app


  postgresql:
    restart: "always"
    image: postgres:12
#    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      - POSTGRES_USER=invenio
      - POSTGRES_DB=invenio
      - POSTGRES_PASSWORD=dbpass123
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "25401:5432"


  nginx:
    restart: "always"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/home/invenio/.virtualenvs/invenio/var/instance/static
      - data_data:/home/invenio/.virtualenvs/invenio/var/instance/data
    links:
      - app
    deploy:
      resources:
        limits:
          memory: 300m

volumes:
  weko3_data:
  static_data:
  data_data:
  conf_data:
  pgsql-data:
  socket: 