version: "3"
services:
  app:
    restart: "always"
    build: .
    ports:
      - "5001:5000"
    container_name: app
    command: uwsgi --ini uwsgi.ini
    links:
      - postgresql
    volumes:
      - ./app:/code


  postgresql:
    restart: "always"
    image: postgres:12
#    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      - POSTGRES_USER=invenio
      - POSTGRES_DB=invenio
      - POSTGRES_PASSWORD=dbpass123
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "25401:5432"


  nginx:
    restart: "always"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/code
    links:
      - app
    deploy:
      resources:
        limits:
          memory: 300m

volumes:
  static_data:
  pgsql-data: